In [2]:
%load_ext autoreload
%autoreload 2

import ast
import re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#import gensim
#from gensim.test.utils import get_tmpfile
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
import json

%matplotlib inline

pd.set_option('display.max_columns', 500)

import pandas as pd 
import numpy as np 
import os
import re

import xgboost
import sklearn

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## XGBoost model takes as input the features extracted by LSI

In [5]:
Y = np.load(r'y.npy')
X = np.load(r'LSI_features.npy')

In [6]:
print(X.shape)
print(Y.shape)

(488413, 300)
(488413,)


## Baseline: dummy model

In [22]:
np.std(Y) ** 2

1.3495673474397945

In [11]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score
regr = xgboost.XGBRegressor()
cross_val_score(regr, X, Y, cv=5, scoring='neg_mean_squared_error')


[20:17:23] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[20:19:26] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[20:21:04] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[20:22:43] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[20:24:45] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


array([-1.35920059, -1.34528227, -1.35292922, -1.34834908, -1.34213636])

## XGBoost model takes as input the features extracted by WORD2VEC

In [21]:
Y = np.load(r'y.npy')
X = np.load(r'WV_features.npy')
print(X.shape)
print(Y.shape)

(488413, 300)
(488413,)


In [16]:
regr = xgboost.XGBRegressor(n_jobs=-1)
CV_W2V = cross_val_score(regr, X, Y, cv=3, scoring='neg_mean_squared_error',n_jobs=-1)

In [23]:
CV_W2V

array([-0.70936819, -0.70180196, -0.70605488])

## XGBoost model takes as input the features extracted by FastText

In [18]:
Y = np.load(r'y.npy')
X = np.load(r'FT_features.npy')
print(X.shape)
print(Y.shape)

(488413, 300)
(488413,)


In [19]:
regr = xgboost.XGBRegressor(n_jobs=-1)
CV_FT = cross_val_score(regr, X, Y, cv=3, scoring='neg_mean_squared_error',n_jobs=-1)

In [20]:
CV_FT

array([-1.3575177 , -1.34930057, -1.34351333])